server:
  port: 10999
  servlet:
    session:
      timeout: 30m
    context-path: /
# 数据库 相关设置
spring:
  application:
    name: wgcloud-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydate?characterEncoding=utf-8&characterSetResults=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    # hikari连接池的参数 相关设置
    hikari:
      # 生效超时
      validationTimeout: 3000
      # 定义获取连接的超时时间。最小250ms,默认30s
      connectionTimeout: 60000
      # 定义连接空闲时间。最小10s,默认10m
      idleTimeout: 60000
      # 定义最小的空闲连接数。推荐不设置。或与最大连接数一致；保持固定的连接数目
      minimumIdle: 10
      # 定义最大的连接数。默认10
      maximumPoolSize: 10
      # 定义连接的最大生命周期。推荐设置该属性。最小30s，默认30m
      maxLifeTime: 60000
      # 从连接池获取到连接后，进行检查的查询语句。推荐设置该属性。默认值为none
      connectionTestQuery: select 1
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
#Mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

master:
    url: localhost:9998

  #tcp监听的端口
tcp:
  port: 9999
  # bossGroup的线程数
boss:
  thread:
    count: 2
  # worker的线程数
worker:
  thread:
    count: 20
  #是否使用长连接
so:
  keepalive:  true
  backlog: 100

async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 20
      queue_capacity: 5000